# Generated by Django 4.1.1 on 2022-09-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='audio_data',
            field=models.JSONField(default='{}'),
        ),
    ]
