# Generated by Django 4.1.1 on 2022-09-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_useraccount_audio_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='userId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='useraccount',
        ),
    ]
