# Generated by Django 4.1.1 on 2022-09-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_useraccount_userid_useraccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='userId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
