# Generated by Django 4.1.1 on 2022-09-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_useraccount_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='userId',
            field=models.CharField(max_length=20),
        ),
    ]
