# Generated by Django 4.1.1 on 2022-09-26 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_useraccount_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticks', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=8), size=8)),
                ('session_id', models.CharField(max_length=20, unique=True)),
                ('step_count', models.CharField(max_length=9, unique=True)),
                ('select_tick', models.CharField(max_length=14)),
            ],
        ),
    ]
